config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  post 'notifications/notify' => 'notifications#notify'
  
  devise_for :users
  resources :users
  resources :promotions do
    resources :charges
    member do
      get :confirmed
      get :pause
    end
    collection do
      get :expired
    end
  end
root 'promotions#index'
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base

  belongs_to :user

  scope :active, -> { where("end_time > ?", DateTime.current) }
  scope :expired, -> { where("end_time < ?", DateTime.current) }

  def is_active?
    DateTime.current < end_time && DateTime.current > start_time
  end

  def value_of_promotion_sold
    buyers*price
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :promotions, dependent: :destroy

  def valid_tel 
    if self.tel[0..2] == "+44"
      return self.tel
    else
     return "+44"+self.tel[1..-1]
   end
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :name, :avatar, :address, :postcode, :city, :tel, :website, :facebook, :twitter, :remote_avatar_url, :role) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :name, :avatar, :address, :postcode, :city, :tel, :website, :facebook, :twitter, :remote_avatar_url, :role) }
    devise_parameter_sanitizer.for(:sing_in) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :name, :avatar, :address, :postcode, :city, :tel, :website, :facebook, :twitter, :remote_avatar_url, :role) }
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  skip_before_action :verify_authenticity_token


  def create
    @promotion = Promotion.find(params[:promotion_id])
    @amount = @promotion.price*100

    business_number = @promotion.user.valid_tel
    customer_number = current_user.valid_tel

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount.to_i,
      :description => @promotion.pitch,
      :currency    => 'gbp'
    )

    client = Twilio::REST::Client.new Rails.application.secrets.twilio_account_sid, Rails.application.secrets.twilio_auth_token

    customer_response = send_customer_text(client, customer_number)
    business_response = send_business_text(client, business_number)

    logger.info "customer response is " + customer_response.status
    logger.info "business response is " + business_response.status

  rescue Stripe::CardError => e
    flash[:error] = e.message
  ensure
    @promotion.buyers += 1
    @promotion.save
    redirect_to confirmed_promotion_path(@promotion)
  end

  def send_customer_text(client, customer_number)
    client.messages.create(
    from: '+441904500767',
    to: customer_number,
    body: "Thank you for making an order with GetLunch, your order of #{@promotion.pitch}, will be ready for collection in 20mins.
      #{@promotion.user.name} 
      #{@promotion.user.address}
      #{@promotion.user.postcode}"
    )
  end

  def send_business_text(client, business_number)
    client.messages.create(
    from: '+441904500767',
    to: business_number,
    body: "#{current_user.name} has just ordered #{@promotion.pitch}"
    )
  end
  
end

app/controllers/concerns/webhookable.rb
module Webhookable
extend ActiveSupport::Concern
 
  def set_header
          response.headers["Content-Type"] = "text/xml"
  end
 
  def render_twiml(response)
          render text: response.text
  end
 
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
 
  skip_before_action :verify_authenticity_token

 
  def notify

    client = Twilio::REST::Client.new Rails.application.secrets.twilio_account_sid, Rails.application.secrets.twilio_auth_token

    message = client.messages.create from: '+15005550006', to: '+447960577601', body: 'Learning to send SMS you are.'

    if message.status == 'queued'
      render plain: 'twilio is working'
      # puts 'success'
    else
      render plain: 'its brokes'
      # puts 'fail'
    end
  end

  
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController

    before_action :find_promotion, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:show, :index]

    def index
      @promotions = Promotion.active.all.order("created_at DESC")
      # @promotions = Promotion.paginate(:page => params[:page], :per_page => 12)
    end

    def expired
      @promotions = Promotion.expired
      # render :index
    end

    def show
    end

    def new
      @promotion = current_user.promotions.build
    end

    def create
      @promotion = current_user.promotions.build(promotion_params)
      
      if @promotion.save
        redirect_to @promotion
      else
        render 'new'
      end
    end

    def edit
    end

    def update
      if @promotion.update(promotion_params)
        redirect_to @promotion
      else
        render 'edit'
      end
    end

    def destroy
      @promotion.destroy
      redirect_to root_path
    end

    def confirmed
      @promotion = Promotion.find(params[:id])
    end

    def pause
      @promotion = Promotion.find(params[:id])
      @promotion.end_time = Time.now
      @promotion.save
      redirect_to user_path(current_user)
    end

    private

    def find_promotion
      @promotion = Promotion.find(params[:id])
    end

    def promotion_params
      params.require(:promotion).permit(:pitch, :description, :price, :available_on_date, :start_time, :end_time, :cuisine, :hotness, :user_id, :image)
    end

end

app/controllers/twilio_controller.rb
require 'twilio-ruby'
 
class TwilioController < ApplicationController
  include Webhookable
 
  after_filter :set_header
 
  skip_before_action :verify_authenticity_token
 
  def voice
    response = Twilio::TwiML::Response.new do |r|
      r.Say 'Hey there. Congrats on integrating Twilio into your Rails 4 app.', :voice => 'alice'
         r.Play 'http://linode.rabasa.com/cantina.mp3'
    end
 
    render_twilio response
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

    def index
      @user = User.all
    end

    def show
      @user = User.find(params[:id])

      @active_promotions = @user.promotions.active.order("created_at DESC")
      @expired_promotions = @user.promotions.expired.order("created_at DESC")

      @total_of_all_promotions_sold = 0
      @user.promotions.each do |promo|
        @total_of_all_promotions_sold += promo.buyers
      end

      @total_sum_of_all_sales = 0
      @user.promotions.each do |promo|
        @total_sum_of_all_sales += promo.price * promo.buyers
      end

        @promotion_count = @user.promotions.length
    end

    def edit
      @user = User.find(params[:id])
    end


    private
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def resource_name
     :user
   end

   def resource
     @resource ||= User.new
   end

   def devise_mapping
     @devise_mapping ||= Devise.mappings[:user]
   end
   
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/_stripe_form.html.haml
= form_tag promotion_charges_path(promotion) do
  %script.stripe-button{"data-amount" => promotion.price*100, "data-description" => promotion.pitch, "data-currency" => "gbp", "data-key" => Rails.configuration.stripe[:publishable_key], :src => "https://checkout.stripe.com/checkout.js"}

app/views/promotions/_form.html.erb
<%= simple_form_for @promotion do |f| %>

  <div class="form-group">
    <%= f.input :pitch, maxlength: 100 %>
  </div>

  <div class="form-group">
    <%= f.file_field :image, required: true %>
  </div>

  <div class="form-group">
    <%= f.input :description %>
  </div>

  <div class="form-group">
    <%= f.input :price %>
  </div>

  <div class="form-inline">
    <%= f.input :start_time %>
  </div>

  <div class="form-inline">
    <%= f.input :end_time %>
  </div>

  <div class="form-group">
    <%= f.input :cuisine %>
  </div>


  <%= f.button :submit %>

<% end %>

app/views/promotions/_promotion.html.erb
<div class="row">
  <div class="well dashboard-promotion-card col-md-12">
    <div class="dashboard-image col-md-4">
      <%= image_tag promotion.image %>
    </div>
    <div class="col-md-8">
      <div class="dashboard-promotion-card-timer">
        <div class="promotion_content" id="promotion_content<%= promotion.id %>">
          <%= hidden_field_tag "promotion_from", promotion.start_time, :id => "promotion_from_#{promotion.id}", :class => "promotion_from" %>
          <%= hidden_field_tag "promotion_to", promotion.end_time, :id => "promotion_to_#{promotion.id}", :class => "promotion_to" %>
          <h4 class="countdown" id="countdown_<%= promotion.id %>">-- Days --Hours --</h4>
        </div>
      </div>
      <div class="dashboard-content">
        <h3><%= promotion.pitch %></h3>
        <p><%= promotion.description %></p>
        <table class="table">
          <tbody>
            <tr>
              <td>Price: </td>
              <td>&pound <%= promotion.price %></td>
            </tr>
            <tr>
              <td>Sales: </td>
              <td><%= promotion.buyers %></td>
            </tr>
            <tr>
              <td>Revenue: </td>
              <td>&pound <%= promotion.value_of_promotion_sold %></td>
            </tr> 
          </tbody>
        </table>
        <div class="dashboard-functions">
          <%= link_to "View", promotion_path(promotion), class:"btn btn-success"%>  
          <% if @user == current_user %>
            <%= link_to "Edit", edit_promotion_path(promotion), class:"btn btn-warning" %>
          <% if promotion.is_active? %>
            <%= link_to "Stop", pause_promotion_path(promotion), class:"btn btn-danger"%>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/promotions/_right_column_show.html.erb
<div class="col-md-5 map-address">

  <div class="row" id="map-container">
    <div id="map-canvas"></div>
  </div>

  <div class="row business-location-info" >  
    <div class="business-address col-md-5" id="address">
      <h4><%= @promotion.user.address %></h4>
      <h4><%= @promotion.user.city %></h4>
      <h4><%= @promotion.user.postcode %></h4>
    </div>
    <div class="walking-time-distance col-md-5">
      <h4 class="distance"><i class="fa fa-street-view "></i></h4>
      <h4 class="duration"><i class="fa fa-clock-o "></i></h4> 
    </div>
  </div>
</div>  

<div class="col-md-5" style="margin: 0px">
  <div class="row stripe" style=" margin-left: 0;margin-right: -30px">
    <% if @promotion.is_active? %>
      <% if user_signed_in? %>
        <div class="stripe-form col-md-12" style="margin: 15px 0 15px 0">
          <center><%= render "charges/stripe_form", promotion: @promotion %></center>
        </div>
      <% else %>
        <div class="stripe-form col-md-12" style="margin: 15px 0 15px 0">
          <h4 style="margin-top: 0px; margin-bottom: 0px;"><center>Please <button type="button" class="btn btn-default navbar-btn"data-target="#sign_in" data-toggle="modal" style="margin-top: 0px">Sign In </button> or <button type="button" class="btn btn-default navbar-btn"data-target="#sign_up_customer" data-toggle="modal" type="button" style="margin-top: 0px">Sign Up </button> to purchase.<center></h4>
        </div>
      <% end %>
    <% else %>
      <div class="stripe-form col-md-12" style="margin: 15px 0 15px 0">
        <h1>This deal has now ended.</h1>
      </div>
    <% end %>
  </div>
</div>



<div class="col-md-5" style="margin: 0px">
  <div class="row" style="margin: 0px -30px 10px 0; background: white; padding: 10px">

    <h4><center>Share</center></h4>

    <a href="http://twitter.com/home?status=@getluch Cant wait to get stuck into - <%= @promotion.pitch %>!! from @<%=@promotion.user.name %>" title="Share on Twitter" target="_blank" class="btn btn-twitter"><i class="fa fa-twitter"></i> Twitter</a>

    <a href="https://www.facebook.com/sharer/sharer.php?u=@getluch Cant wait to luck into <%= @promotion.pitch %>!! #getluch" title="Share on Facebook" target="_blank" class="btn btn-facebook"><i class="fa fa-facebook"></i> Facebook</a>

    <a href="https://plus.google.com/share?url=@getluch Cant wait to luck into <%= @promotion.pitch %>!! #getluch" title="Share on Google+" target="_blank" class="btn btn-googleplus"><i class="fa fa-google-plus"></i> Google+</a>

    <a href="mailto:?subject=Look%20what%20I%20just%20got%20for%20lunch!!&body=<%= @promotion.pitch %>" title="Share on Email" class="btn btn-email"><i class="fa fa-envelope-o"></i> Email</a>
  </div>
</div>

app/views/promotions/confirmed.html.erb
<div class="jumbotron">
  <div class="well jumbotron">
    <h2><center>Purchase complete :)</center></h2>
    <h3>Your GetLunch purchase of <strong><em><%= @promotion.pitch %></em></strong> for <strong>&pound<%= @promotion.price %></strong> has now been sucessfully processed, you will recieve a text message shortly confirming pickup time.</h3>
    <center>
      <div class="jumbotron btn-group inline">
        <%= link_to "Return to deal", promotion_path(@promotion), class:"btn btn-success"%>
        <%= link_to "Browse more deals", root_path, class:"btn btn-success"%>
      </div>
    </center>
  </div>
</div>

app/views/promotions/edit.html.erb
<div class="container">
  <div class= "wrapper form">
    <h1>Edit Promotion</h1>
    <%= render "form" %>
  </div>
</div>

app/views/promotions/new.html.erb
<div class="container">
  <div class= "wrapper form">
    <h1>New Promotion</h1>
    <%= render "form" %>
  </div>
</div>

app/views/promotions/show.html.erb
<div class="wrapper">
  <div class="panel-body">

    <!-- left columm -->
    <div class="row">
      <div class="col-md-7 promotion-show">
        <div class="promotion-image">
          <%= image_tag @promotion.image %>
        </div>
        <div class="promotion-price">
          <h1>&pound<%= number_with_precision(@promotion.price, precision: 2)   %></h1>
        </div>
        <div class="promotion-pitch">
          <h1><em><%= @promotion.pitch %></em></h1>
        </div>
        <div class="promotion-countdown">
          <div class="promotion_content" id="promotion_content<%= @promotion.id %>">
            <%= hidden_field_tag "promotion_from", @promotion.start_time, :id => "promotion_from_#{@promotion.id}", :class => "promotion_from" %>
            <%= hidden_field_tag "promotion_to", @promotion.end_time, :id => "promotion_to_#{@promotion.id}", :class => "promotion_to" %>
            <h1 class="countdown" id="countdown_<%= @promotion.id %>">-- Days --Hours -- Mins -- Secs</h1>
          </div>
        </div>
        <div class="promotion-information">
          <div class="promotion-business">
            <h1><%= @promotion.user.name %></h1>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="promotion-description">
                <p class="lead"><%= @promotion.description %></p>
              </div>
            </div>
          </div>         
        </div>
      </div>
      
      <div>
      <%= render "right_column_show" %> 
      </div>
    </div>


  </div>
</div>

app/views/promotions/show1.html.haml
.container
  .panel-body
    .row
      .col-md-7
        .
          = image_tag @promotion.user.avatar.show.url
          %h2= @promotion.user.name
          %div{class: "promotion_content", id: "promotion_content#{@promotion.id}"}
            = hidden_field_tag "promotion_from", @promotion.start_time, :id => "promotion_from_#{@promotion.id}", :class => "promotion_from"
            = hidden_field_tag "promotion_to", @promotion.end_time, :id => "promotion_to_#{@promotion.id}", :class => "promotion_to"
            %h4{id: "countdown_#{@promotion.id}", :class => "countdown"} -- Days --Hours -- Mins -- Secs


            %h4= @promotion.pitch
            %h4= @promotion.description
            %h4= number_to_currency(@promotion.price, unit: '£')
            %h4= @promotion.available_on_date
            %h4= @promotion.cuisine

            -if current_user
              - if current_user.id == @promotion.user.id
                =link_to "Edit", edit_promotion_path(@promotion)
                =link_to "Delete", promotion_path(@promotion), method: :delete


            - if @promotion.is_active?
              - if user_signed_in?
                =render "charges/stripe_form", promotion: @promotion
              - else
                please login
            - else
              promo ended

          / - if user_signed_in? && @promotion.active_promotion
          /   =render "charges/stripe_form", promotion: @promotion
          / - else
          /   %strong Please login 

        .col-md-5
          #map-container
            #map-canvas

          #address
            %h4.duration
            %h4.distance
            %h4= @promotion.user.name
            %h4= @promotion.user.address
            %h4= @promotion.user.city
            %h4= @promotion.user.postcode


    <div class="promotion-countdown">
          <div class="promotion_content" id="promotion_content<%= @promotion.id %>">
            <%= hidden_field_tag "promotion_from", @promotion.start_time, :id => "promotion_from_#{@promotion.id}", :class => "promotion_from" %>
            <%= hidden_field_tag "promotion_to", @promotion.end_time, :id => "promotion_to_#{@promotion.id}", :class => "promotion_to" %>
            <h4 class="countdown" id="countdown_<%= @promotion.id %>">-- Days --Hours -- Mins -- Secs</h4>
          </div>
        </div>


<div class="row col-md-5 map-address">
        <div class="col-md-12" id="map-container">
          <div id="map-canvas"></div>
        </div>
        <div class="row business-location-info col-md-12" >  
          <i width="40"class="fa fa-map-marker fa-5x col-md-2">
          </i>
          <div class="business-address col-md-5" id="address">
            <h4><%= @promotion.user.address %></h4>
            <h4><%= @promotion.user.city %></h4>
            <h4><%= @promotion.user.postcode %></h4>
          </div>
          <div class="walking-time-distance col-md-5">
            <h4 class="distance"><i class="fa fa-street-view"></i></h4>
            <h4 class="duration"><i class="fa fa-clock-o"></i></h4> 
          </div>
        </div>
        <div class="row col-md-12 stripe">
          <% if @promotion.is_active? %>
            <% if user_signed_in? %>
              <%= render "charges/stripe_form", promotion: @promotion %>
            <% else %>
              please login
            <% end %>
          <% else %>
            promo ended
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="col-sm-6 col-md-3">
    <%= @user.name %>
  </div>
<%end%>

app/views/users/show.html.erb
<div class="wrapper">
  <div class="row">

    <div class="stat-1 col-md-4 well" id="stat-1">
      <h3><center>Promotions Created</center></h3>
      <h4><center><%= @promotion_count %></h4>
    </div>

    <div class="stat-2 col-md-4 well">
      <h3><center>Total Revenue</center></h3>
      <h4><center><%= @total_sum_of_all_sales %></center></h4>
    </div>

    <div class="stat-3 col-md-4 well">
      <h3><center>Total Promotions Sold</center></h3>
      <h4><center><%= @total_of_all_promotions_sold %></center></h4>
    </div>
  </div>

  <h2>Active promotions: </h2>
  <div class="row">
    <%= render @active_promotions, partial: "promotions/promotion" %>
  </div>

  <% unless @expired_promotions.count <= 0 %>
    <h2> Expired promotions: </h2>
    <div class="row">
      <%= render @expired_promotions, partial: "promotions/promotion" %>
    </div>
  <% end %>
  
  
</div>